# Generated by Django 3.2.3 on 2021-05-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_table', models.IntegerField()),
                ('page', models.TextField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('body', models.TextField()),
                ('ts_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_table', models.IntegerField()),
                ('path', models.TextField()),
                ('filename', models.TextField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('ts_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type_wood', models.TextField()),
                ('type_epox', models.TextField()),
                ('color_epox', models.TextField()),
                ('note', models.TextField()),
                ('ts_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'tables',
                'managed': False,
            },
        ),
    ]
