# Generated by Django 3.2.3 on 2021-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belatafels_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
    ]
