# Generated by Django 3.2.3 on 2021-05-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belatafels_api', '0003_auto_20210513_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BelatafelsApiHero',
        ),
    ]
