# Generated by Django 3.2.3 on 2021-05-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belatafels_api', '0004_delete_belatafelsapihero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id_table', models.IntegerField()),
                ('path', models.TextField()),
                ('filename', models.TextField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('ts_created', models.DateTimeField()),
                ('photo_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('name', models.TextField()),
                ('type_wood', models.TextField()),
                ('type_epox', models.TextField()),
                ('color_epox', models.TextField()),
                ('note', models.TextField()),
                ('ts_created', models.DateTimeField()),
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
